### ISSUE TITLE
Edge Routes infinite loading on Remix v2

### ISSUE THREAD

**Issue by robipop22** [vercel/remix#58]
I tried upgrading to Latest version 2.0.1 from 1.18.1. 

All the future flags are enabled, they are working fine.

When you go to a node route, it's fine.

If you navigate to an "edge" route, it's fine.

But if you hard refresh the edge route, it will get stuck and just loads forever.

you can test on the [dnb-stack](https://github.com/robipop22/dnb-stack) which is open source. 

https://dnb-stack.vercel.app/edge

We are also working on a project where we are stuck on 1.17.0 because of the infinite loading.

Could you please take also a look, thanks!

**Comment by cb1kenobi** [comment]
I've tried to reproduce with both a minimal test case (https://remixfun2-hdwyd3tio-chrisbarber.vercel.app/) and deploying the dnb-stack app (https://remix-dnb-stack-m9ao0cqow-chrisbarber.vercel.app/edge). In both cases, they seem finish loading successfully when doing a hard refresh. I'm testing using Chrome 117 on macOS.

What browser were you using?

**Comment by cb1kenobi** [comment]
FWIW, I notice there's large number of images being downloaded from S3. While there's nothing wrong with this, perhaps one of them was preventing the page from loading?

**Comment by cb1kenobi** [comment]
Couple more questions...

How are you deploying? From git? `vc deploy`? `vc build && vc deploy --prebuilt`?

Which package manager? Are you using a lock file? Is it committed to git? Is it up-to-date with the package.json?

**Comment by robipop22** [comment]
@cb1kenobi  I just deployed a new with version 2 and we are getting this in logs: 

`ps {
  status: 405,
  statusText: 'Method Not Allowed',
  internal: true,
  data: 'Error: Invalid request method "OPTIONS"',
  error: Error: Invalid request method "OPTIONS"
    at (node_modules/.pnpm/@remix-run+router@1.6.3/node_modules/@remix-run/router/dist/router.js:3656:0)
    at (node_modules/.pnpm/@remix-run+router@1.6.3/node_modules/@remix-run/router/dist/router.js:2651:0)
    at (node_modules/.pnpm/@remix-run+server-runtime@1.17.0/node_modules/@remix-run/server-runtime/dist/esm/server.js:159:0)
    at (node_modules/.pnpm/@remix-run+server-runtime@1.17.0/node_modules/@remix-run/server-runtime/dist/esm/server.js:57:0)
}`

![image](https://github.com/vercel/remix/assets/13586721/b0efc6ee-eb08-4419-9114-e03344065440)

**Comment by cb1kenobi** [comment]
@robipop22 the error stack seems to indicate you are using `@remix-run/router@1.6.3` and `@remix-run/server-runtime@1.17.0`. This would indicate that maybe you're not fully up-to-date and that there's a mismatch between the Remix package versions. If you're using Remix 2.0.1, then you should probably be using `@remix-run/router@1.9.0` and `@remix-run/server-runtime@2.0.1`. Can you try running `pnpm upgrade` to regen the `pnpm-lock.yaml`, then deploy and see if that resolves the issue.

**Comment by robipop22** [comment]
@cb1kenobi  thanks for looking also. 
It seems that the lock file had that version cached, weirdly enough it did not get overwritten when manually doing upgrades, but it seems that `pnpm upgrade` did fix that in the end.

Thank you! 

I'm going to close the issue as it was solved.

**Comment by cb1kenobi** [comment]
@david-crespo we looked at a few of your example pages and it's super interesting that it takes exactly 1 minute for a page to finish loading. It's also interesting that the page takes 1 minute with JavaScript disabled.

I suspect your issue is unrelated to the original reported issue. I'm tempted to suggest it's a Remix issue, possibly related to HTTP2.

When I run `time curl -i https://rfd-site-izpso5nw4-oxidecomputer.vercel.app/rfd/0002`, it returns most of the page immediately, but then hang before sending the last 450 bytes give or take.

This doesn't sound like a Vercel caching issue. It could be related to the Vercel proxy issue and HTTP2, but that doesn't explain why it works sometimes and not others. It's also not a browser issue or browser plugin issue.

We can't seem to reproduce in an isolated test project. If you'd like, you can go into the project settings and on the Security page, enable the "customer success code visibility" setting so we can search for clues.

**Comment by david-crespo** [comment]
Thanks for looking at it. I tried upgrading this site to Remix v2. I also couldn't repro independently and I tried pretty hard to figure out what was unique about what we're doing. Because the response size seems to determine something, I also thought it could be a Vercel proxy thing. I'll talk to my team and see if we have any issue with turning on the code visibility thing. It's probably fine. Thanks!

**Comment by david-crespo** [comment]
@cb1kenobi at great psychic cost, I have a minimal (and I mean minimal) repro for you.

https://github.com/oxidecomputer/vercel-timeout

* good https://vercel-timeout.vercel.app/?size=16000
* bad https://vercel-timeout.vercel.app/?size=17000
* bad https://vercel-timeout.vercel.app/?size=64000
* good https://vercel-timeout.vercel.app/?size=65000

**Comment by cb1kenobi** [comment]
@david-crespo Amazing work! I'll take a peek and share with the team.

**Comment by cb1kenobi** [comment]
@david-crespo the Edge Network team is investigating. Things appear to work when specifying an accept encoding:

```
time curl -i https://vercel-timeout.vercel.app/\?size\=16181 -sH 'Accept-encoding: gzip'
```

We stream in 16KB chunks, so that explains the boundary. The team will keep looking into the issue. We appreciate your patience!

**Comment by smaeda-ks** [comment]
Hi @david-crespo, I'm from Vercel, too.

We discussed this a bit internally, and saw that we had some problems with Remix streamings deployed on our serverless functions. That said, we've pushed some changes that should fix the reported issue. Could you try redeploying the app and test it again? Let us know how it goes

We're sorry for the trouble! and really appreciate your detailed report.

**Comment by david-crespo** [comment]
Looks good!

https://vercel-timeout-czduxzeqr-oxidecomputer.vercel.app/?size=32000

Thanks for the quick fix. Any chance you could say a little more about what it was?

**Comment by smaeda-ks** [comment]
@david-crespo unfortunately, we cannot disclose many details about the root cause, but we had a bug in our runtime that appears to be coming from the Node.js core itself. We've worked it around.
